application:
  issue:
    maxAllowedBooks: 2
#    max-allowed-books: 2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryMSDB?createDatabaseIfNotExist=TRUE
    username: root
    password: lokation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: issue-microservice
server:
  error:
    include-message: always
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
