spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryMSDB?createDatabaseIfNotExist=TRUE
    username: root
    password: lokation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: reader-microservice
server:
  error:
    include-message: always
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka